### ISSUE TITLE
Cannot GET /api/doc

### ISSUE THREAD

**Issue by highfellow** [TheKinrar/mastodon-instances#55]
When I try to retrieve the API documentation, I get the error 'Cannot GET /api/doc'.

**Comment by TheKinrar** [comment]
Fixed, thanks. Forgot to rebuild the api doc.

**Comment by CirKu17** [comment]
@TheKinrar I still see this message when I follow the link from the topbar menu in the API section.
The link that works is /api/1.0/doc .
![Screenshot_2020-03-03 Mastodon instances](https://user-images.githubusercontent.com/833603/75812388-718c9800-5d8e-11ea-88e0-1e369d65bb1d.png)

**Comment by TheKinrar** [comment]
Fixed again, thanks.
